version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: reserveiDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../Database/reserveiDB.sql:/docker-entrypoint-initdb.d/reserveiDB.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  api:
    build:
      context: ../ReserveiAPI
    container_name: api_container
    restart: always
    ports:
      - "7096:80"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=reserveiDB;Username=postgres;Password=123456
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build:
      context: ../frontends
      args:
        VITE_API_URL: http://localhost:7096
    container_name: frontend_container
    restart: always
    ports:
      - "5173:80"
    depends_on:
      api:
        condition: service_started

volumes:
  postgres_data:
